language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.1.8
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false